name: Call reusable workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    secrets: inherit
    uses: iacabezasbaculima/reusableworkflows-sandbox/.github/workflows/helloworld.yml@main
    with:
      who-to-greet: ${{ github.action_repository }}
